# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bsvar_s4_sv_cpp <- function(SS, Y, X, prior, VB, starting_values, thin = 100L) {
    .Call(`_bsvarTVPs_bsvar_s4_sv_cpp`, SS, Y, X, prior, VB, starting_values, thin)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_bsvarTVPs_RcppExport_registerCCallable', PACKAGE = 'bsvarTVPs')
})
