# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rodriguez_Yam_2004 <- function(mu, Sig, A, l, u, x) {
    .Call(`_bsvarTVPs_Rodriguez_Yam_2004`, mu, Sig, A, l, u, x)
}

AN <- function(mu, rho) {
    .Call(`_bsvarTVPs_AN`, mu, rho)
}

logf_w1 <- function(x, P, m1, m2, sig1, sig2, gam1, gam2, T) {
    .Call(`_bsvarTVPs_logf_w1`, x, P, m1, m2, sig1, sig2, gam1, gam2, T)
}

logtar_w1 <- function(x, gam1, gam2, invVw10, w10, T) {
    .Call(`_bsvarTVPs_logtar_w1`, x, gam1, gam2, invVw10, w10, T)
}

exact_sampling_w1 <- function(gam1, gam2, T, neww1, w1, invVw10, w10) {
    .Call(`_bsvarTVPs_exact_sampling_w1`, gam1, gam2, T, neww1, w1, invVw10, w10)
}

construct_LR <- function(zeroB_R, signB_R) {
    .Call(`_bsvarTVPs_construct_LR`, zeroB_R, signB_R)
}

sample_Theta0_Hou24_heterosk1 <- function(aux_Theta0, aux_A, aux_sigma, Y, X, prior, restrictions, debug = FALSE) {
    .Call(`_bsvarTVPs_sample_Theta0_Hou24_heterosk1`, aux_Theta0, aux_A, aux_sigma, Y, X, prior, restrictions, debug)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_bsvarTVPs_RcppExport_registerCCallable`)
})
